# Generated by Django 2.0.4 on 2019-07-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='protocol',
            field=models.CharField(default='http', max_length=20),
        ),
        migrations.AddField(
            model_name='step',
            name='nosqlCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='sqlCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='carryId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='out_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='email',
            name='passwd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modules',
            name='Modules_desc',
            field=models.CharField(blank=True, max_length=200, verbose_name='模块描述'),
        ),
    ]
